env:
  node: true
  es6: true
  jest: true
  commonjs: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - node_modules
  - gatsby-browser.jsx
  - gatsby-config.mjs
  - gatsby-node.js
  - gatsby-ssr.jsx
  - index.ts

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - tsconfig.eslint.json
  extraFileExtensions:
    - .json
  ecmaFeatures:
    jsx: true

plugins:
  - '@typescript-eslint'

settings:
  react:
    version: detect
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
  import/extensions:
    - .ts
    - .tsx

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:github/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended

rules:
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-var-requires': off
  import/no-commonjs: off
  no-console: off
  no-shadow: off
  no-unused-vars: off
