env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - .cache
  - node_modules
  - public

parser: eslint-mdx

extends:
  - plugin:mdx/recommended
  - plugin:prettier/recommended
  - plugin:react/recommended

parserOptions:
  extensions:
    - mdx
  markdownExtensions:
    - md
  ignoreRemarkConfig: false

settings:
  mdx/code-blocks: true
  mdx/remark: true
  react:
    version: detect

rules:
  react/no-unescaped-entities: off
