settings:
  bullet: '-'
  closeAtx: false
  emphasis: '_'
  fences: true
  incrementListMarker: false
  strong: '*'

plugins:
  preset-lint-consistent:
  preset-lint-recommended:
  preset-lint-markdown-style-guide:
  preset-prettier:

  # Custom settings
  remark-lint-maximum-heading-length: false
  remark-lint-no-heading-punctuation: false
