settings:
  bullet: '-'
  closeAtx: false
  emphasis: '_'
  fences: true
  incrementListMarker: false
  strong: '*'
plugins:
  - remark-preset-lint-consistent
  - remark-preset-lint-markdown-style-guide
  - remark-preset-prettier
  - - remark-lint-maximum-heading-length
    - false
